# Generated by Django 5.0 on 2023-12-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_gallerymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerymodel',
            options={'verbose_name': 'gallery', 'verbose_name_plural': 'galleries'},
        ),
    ]
