# Generated by Django 5.0 on 2023-12-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_menumodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumodel',
            name='discount',
        ),
        migrations.AddField(
            model_name='menumodel',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
