# Generated by Django 5.0 on 2023-12-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_reservation_created_at_reservation_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'reservation', 'verbose_name_plural': 'reservations'},
        ),
    ]
